(()=>{"use strict";
const SUPABASE_URL="https://wcnblqtyupqrvnisquev.supabase.co";
const SUPABASE_KEY="sb_publishable_kEaT52pxurL9ZDnsMOLv3Q_lKFLN7DF";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let meUser=null,profile=null,data={students:[],groups:[],records:[],profiles:[]};
const surahs=["Al-Fatihah","Al-Baqarah","Ali 'Imran","An-Nisa'","Al-Ma'idah","Al-An'am","Al-A'raf","Al-Anfal","At-Taubah","Yunus","Hud","Yusuf","Ar-Ra'd","Ibrahim","Al-Hijr","An-Nahl","Al-Isra'","Al-Kahf","Maryam","Ta-Ha","Al-Anbiya'","Al-Hajj","Al-Mu'minun","An-Nur","Al-Furqan","Asy-Syu'ara'","An-Naml","Al-Qasas","Al-'Ankabut","Ar-Rum","Luqman","As-Sajdah","Al-Ahzab","Saba'","Fatir","Ya-Sin","As-Saffat","Sad","Az-Zumar","Ghafir","Fussilat","Asy-Syura","Az-Zukhruf","Ad-Dukhan","Al-Jasiyah","Al-Ahqaf","Muhammad","Al-Fath","Al-Hujurat","Qaf","Az-Zariyat","At-Tur","An-Najm","Al-Qamar","Ar-Rahman","Al-Waqi'ah","Al-Hadid","Al-Mujadilah","Al-Hasyr","Al-Mumtahanah","As-Saff","Al-Jumu'ah","Al-Munafiqun","At-Tagabun","At-Talaq","At-Tahrim","Al-Mulk","Al-Qalam","Al-Haqqah","Al-Ma'arij","Nuh","Al-Jinn","Al-Muzzammil","Al-Muddassir","Al-Qiyamah","Al-Insan","Al-Mursalat","An-Naba'","An-Nazi'at","'Abasa","At-Takwir","Al-Infitar","Al-Mutaffifin","Al-Insyiqaq","Al-Buruj","At-Tariq","Al-A'la","Al-Gasyiyah","Al-Fajr","Al-Balad","Asy-Syams","Al-Lail","Ad-Duha","Asy-Syarh","At-Tin","Al-'Alaq","Al-Qadr","Al-Bayyinah","Az-Zalzalah","Al-'Adiyat","Al-Qari'ah","At-Takatsur","Al-'Asr","Al-Humazah","Al-Fil","Quraisy","Al-Ma'un","Al-Kausar","Al-Kafirun","An-Nasr","Al-Lahab","Al-Ikhlas","Al-Falaq","An-Nas"];
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function toast(m,bad=false){let t=$("#toast");t.textContent=m;t.style.background=bad?"#a52a21":"";t.className="toast show";clearTimeout(window.__t);window.__t=setTimeout(()=>t.className="toast",2600)}
function closeModal(){$("#modal").innerHTML=""}
function modal(title,body,fn){$("#modal").innerHTML=`<div class="modalbg" id="modalbg"><div class="modalcard"><div class="modalhead"><h2>${title}</h2><button class="icon-btn" type="button" data-close>×</button></div><form id="mf">${body}<div class="actions"><button type="button" class="btn" data-close>Batal</button><button class="btn primary">Simpan</button></div></form></div></div>`;let b=$("#modalbg"),f=$("#mf");$$("[data-close]",b).forEach(x=>x.onclick=closeModal);b.onclick=e=>e.target===b&&closeModal();f.onsubmit=e=>{e.preventDefault();fn(f)}}
function visibleStudents(){return profile.role==="admin"?data.students:data.students.filter(s=>s.ustadz_id===meUser)}
function nameOf(id){return data.profiles.find(x=>x.id===id)?.name||"Belum ditentukan"}
function groupOf(id){return data.groups.find(x=>x.id===id)?.name||"Belum dikelompokkan"}
async function loadData(){let [a,b,c,d]=await Promise.all([sb.from("students").select("*").order("name"),sb.from("groups").select("*").order("name"),sb.from("records").select("*").order("record_date",{ascending:false}),sb.from("profiles").select("*")]);for(const x of[a,b,c,d])if(x.error)throw x.error;data={students:a.data||[],groups:b.data||[],records:c.data||[],profiles:d.data||[]}}
function showErr(x){$("#loginError").textContent=x;$("#loginError").classList.remove("hidden")}
async function login(){
let email=$("#username").value.trim(),p=$("#password").value;
if(SUPABASE_KEY.startsWith("PASTE_"))return showErr("Publishable key Supabase belum diisi.");
let {data:d,error}=await sb.auth.signInWithPassword({email,password:p});
if(error)return showErr(error.message==="Invalid login credentials"?"Email atau password salah.":error.message);
meUser=d.user.id;
let {data:prof,error:pe}=await sb.from("profiles").select("*").eq("id",d.user.id).maybeSingle();
if(pe)return showErr(pe.message);
if(!prof)return showErr("Akun berhasil login, tetapi profil belum dibuat di tabel profiles.");
profile=prof;
await enter()
}
async function enter(){try{await loadData();$("#login").classList.add("hidden");$("#app").classList.remove("hidden");render()}catch(e){showErr(e.message||"Gagal terhubung ke Supabase.")}}
async function logout(){
await sb.auth.signOut();
meUser=null;profile=null;sessionStorage.removeItem("halaqoh_profile");
$("#app").classList.add("hidden");$("#login").classList.remove("hidden");$("#password").value=""
}
function nav(){let admin=profile.role==="admin",items=admin?[["dashboard","⌂","Dashboard"],["students","♙","Santri"],["groups","◈","Kelompok"],["users","♟","Akun Ustadz"],["records","✎","Setoran"],["reports","▣","Rekap"]]:[["dashboard","⌂","Dashboard"],["students","♙","Santri Binaan"],["records","✎","Setoran"],["reports","▣","Rekap"]],p=location.hash.slice(1)||"dashboard";$("#nav").innerHTML=items.map(i=>`<button class="nav-item ${p===i[0]?"active":""}" data-p="${i[0]}"><span class="nav-icon">${i[1]}</span>${i[2]}</button>`).join("");$$(".nav-item").forEach(b=>b.onclick=()=>{location.hash=b.dataset.p;$("#sidebar").classList.remove("open")});let q=(profile.name||"U")[0].toUpperCase();$("#who-name").textContent=profile.name;$("#who-role").textContent=admin?"Administrator":"Ustadz";$("#avatar").textContent=q;$("#top-name").textContent=profile.name;$("#top-role").textContent=admin?"Administrator":"Ustadz";$("#top-avatar").textContent=q;$("#top-date").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function head(t,s,a=""){return `<div class="page-head"><div><span class="eyebrow">HALAQOH TAHFIDZ</span><h1>${t}</h1><p>${s}</p></div><div class="head-actions">${a}</div></div>`}
function stat(i,n,v,s){return `<div class="stat"><div class="stat-icon">${i}</div><span>${n}</span><b>${v}</b><small>${s}</small></div>`}
function dashboard(){let ss=visibleStudents(),rs=data.records.filter(r=>ss.some(s=>s.id===r.student_id)),z=rs.filter(r=>r.type==="Ziyadah").length,m=rs.filter(r=>r.type==="Murajaah").length,av=rs.length?(rs.reduce((a,r)=>a+r.score,0)/rs.length).toFixed(1):"—";return head("Dashboard","Ringkasan perkembangan halaqoh Anda.")+`<div class="stats">${stat("♙","Santri",ss.length,"santri terdaftar")}${stat("✎","Total Setoran",rs.length,"catatan hafalan")}${stat("↗","Ziyadah",z,"setoran baru")}${stat("↻","Murajaah",m,"pengulangan")}</div><div class="grid2"><section class="panel"><div class="panel-title"><h2>Setoran terbaru</h2><button class="text-btn" onclick="location.hash='records'">Lihat semua →</button></div>${rs.slice(0,5).map(r=>{let s=ss.find(x=>x.id===r.student_id);return `<div class="list-row"><div class="avatar">${esc((s?.name||"?")[0])}</div><div style="flex:1"><b>${esc(s?.name||"—")}</b><small>${esc(r.type)} · ${esc(r.from_surah)} ${esc(r.from_ayat)} → ${esc(r.to_surah)} ${esc(r.to_ayat)}</small></div><strong class="score">${r.score}</strong></div>`}).join("")||`<div class="empty">Belum ada setoran.</div>`}</section><section class="panel"><div class="panel-title"><h2>Ringkasan nilai</h2></div><div class="list-row"><span>Rata-rata nilai</span><b class="score">${av}</b></div><div class="list-row"><span>Sangat baik (90+)</span><b>${rs.filter(r=>r.score>=90).length}</b></div><div class="list-row"><span>Perlu murajaah (&lt;80)</span><b>${rs.filter(r=>r.score<80).length}</b></div><div class="quick" style="margin-top:12px"><button onclick="recordModal()">＋ Catat Setoran Baru</button></div></section></div>`}
function students(){let a=profile.role==="admin",ss=visibleStudents();return head(a?"Data Santri":"Santri Binaan",a?"Kelola data santri dan pengelompokan.":"Daftar santri yang dibina oleh Anda.",a?`<button class="btn primary" onclick="studentModal()">＋ Tambah Santri</button>`:"")+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Kelas</th><th>Kelompok</th><th>Ustadz</th><th>Setoran</th>${a?"<th>Aksi</th>":""}</tr></thead><tbody>${ss.map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.class_name||"—")}</td><td>${esc(groupOf(s.group_id))}</td><td>${esc(nameOf(s.ustadz_id))}</td><td>${data.records.filter(r=>r.student_id===s.id).length}</td>${a?`<td><button class="btn" style="background:#fff1ef;color:#a52a21" onclick="delStudent('${s.id}')">Hapus</button></td>`:""}</tr>`).join("")||`<tr><td colspan="${a?6:5}" class="empty">Belum ada santri.</td></tr>`}</tbody></table></div></section>`}
function groups(){return head("Kelompok Halaqoh","Atur kelompok dan ustadz pembina.",`<button class="btn primary" onclick="groupModal()">＋ Buat Kelompok</button>`)+`<section class="cards">${data.groups.map(g=>`<div class="card"><span class="eyebrow">HALAQOH</span><h3>${esc(g.name)}</h3><p>Ustadz pembina<br><b>${esc(nameOf(g.ustadz_id))}</b></p><b>${data.students.filter(s=>s.group_id===g.id).length} santri</b></div>`).join("")||`<div class="empty">Belum ada kelompok.</div>`}</section>`}
function users(){let us=data.profiles.filter(u=>u.role==="ustadz");return head("Akun Ustadz","Kelola akun pembina halaqoh.",`<button class="btn primary" onclick="userModal()">＋ Buat Akun</button>`)+`<section class="cards">${us.map(u=>`<div class="card"><div class="avatar">${esc((u.name||"U")[0])}</div><h3>${esc(u.name)}</h3><p>@${esc(u.username||"")}</p><button class="btn" style="background:#fff1ef;color:#a52a21" onclick="delUser('${u.id}')">Hapus akun</button></div>`).join("")||`<div class="empty">Belum ada akun ustadz.</div>`}</section>`}
function recordModal(){let ss=visibleStudents();if(!ss.length)return toast("Belum ada santri.",true);let opts=surahs.map((s,i)=>`<option value="${i}">${i+1}. ${s}</option>`).join("");modal("Catat Setoran Hafalan",`<div class="formgrid"><label>Santri<select name="studentId">${ss.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></label><label>Jenis Setoran<select name="type"><option value="Ziyadah">📖 Ziyadah — Hafalan baru</option><option value="Murajaah">🔄 Murajaah — Mengulang hafalan</option></select></label><label>Dari Surat<select name="from">${opts}</select></label><label>Dari Ayat<input name="fromAyat" required placeholder="Contoh: 1"></label><label>Sampai Surat<select name="to">${opts}</select></label><label>Sampai Ayat<input name="toAyat" required placeholder="Contoh: 10"></label><label>Tanggal<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Nilai<select name="score"><option value="90">90 — Sangat Baik</option><option value="80">80 — Baik</option><option value="70">70 — Cukup</option><option value="60">60 — Perlu Murajaah</option></select></label><label>Catatan<input name="note"></label></div>`,async f=>{let fi=+f.from.value,ti=+f.to.value;if(ti<fi)return toast("Surat sampai tidak boleh sebelum surat dari.",true);let {error}=await sb.from("records").insert({student_id:f.studentId.value,ustadz_id:meUser,type:f.type.value,from_surah:surahs[fi],from_ayat:f.fromAyat.value.trim(),to_surah:surahs[ti],to_ayat:f.toAyat.value.trim(),score:+f.score.value,note:f.note.value.trim(),record_date:f.date.value});if(error)return toast(error.message,true);closeModal();await loadData();toast("Setoran berhasil disimpan");render()})}
function records(){let ss=visibleStudents(),rs=data.records.filter(r=>ss.some(s=>s.id===r.student_id));return head("Setoran Hafalan","Pantau ziyadah dan murajaah secara terstruktur.",`<button class="btn primary" onclick="recordModal()">＋ Catat Setoran</button>`)+`<section class="panel"><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Santri</th><th>Jenis</th><th>Rentang Hafalan</th><th>Nilai</th><th>Catatan</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${r.record_date}</td><td><b>${esc(ss.find(s=>s.id===r.student_id)?.name||"—")}</b></td><td><b style="color:${r.type==="Ziyadah"?"var(--g)":"#a87522"}">${esc(r.type)}</b></td><td>${esc(r.from_surah)} ${esc(r.from_ayat)} → ${esc(r.to_surah)} ${esc(r.to_ayat)}</td><td class="score">${r.score}</td><td>${esc(r.note||"—")}</td></tr>`).join("")||`<tr><td colspan="6" class="empty">Belum ada setoran.</td></tr>`}</tbody></table></div></section>`}
function reports(){let ss=visibleStudents(),rs=data.records.filter(r=>ss.some(s=>s.id===r.student_id));return head("Rekap Perkembangan","Laporan ringkas dan siap dicetak.",`<button class="btn primary" onclick="pdf()">↓ Unduh PDF</button>`)+`<section class="panel"><div class="report-summary"><div><span>Total Santri</span><b>${ss.length}</b></div><div><span>Total Setoran</span><b>${rs.length}</b></div><div><span>Ziyadah</span><b>${rs.filter(r=>r.type==="Ziyadah").length}</b></div><div><span>Murajaah</span><b>${rs.filter(r=>r.type==="Murajaah").length}</b></div></div><div class="table-wrap"><table><thead><tr><th>Santri</th><th>Ziyadah</th><th>Murajaah</th><th>Rata-rata</th><th>Hafalan terakhir</th></tr></thead><tbody>${ss.map(s=>{let x=rs.filter(r=>r.student_id===s.id),av=x.length?(x.reduce((a,r)=>a+r.score,0)/x.length).toFixed(1):"—",last=x[0];return `<tr><td><b>${esc(s.name)}</b></td><td>${x.filter(r=>r.type==="Ziyadah").length}</td><td>${x.filter(r=>r.type==="Murajaah").length}</td><td class="score">${av}</td><td>${last?esc(last.from_surah)+" "+esc(last.from_ayat)+" → "+esc(last.to_surah)+" "+esc(last.to_ayat):"—"}</td></tr>`}).join("")||`<tr><td colspan="5" class="empty">Belum ada data.</td></tr>`}</tbody></table></div></section>`}
function studentModal(){let gs=data.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join("");modal("Tambah Santri",`<div class="formgrid"><label>Nama Lengkap<input name="name" required></label><label>Kelas<input name="className"></label><label>Kelompok<select name="groupId"><option value="">Belum dikelompokkan</option>${gs}</select></label></div>`,async f=>{let g=data.groups.find(x=>x.id===f.groupId.value),{error}=await sb.from("students").insert({name:f.name.value.trim(),class_name:f.className.value.trim(),group_id:g?.id||null,ustadz_id:g?.ustadz_id||null});if(error)return toast(error.message,true);closeModal();await loadData();toast("Santri berhasil ditambahkan");render()})}
function userModal(){modal("Buat Akun Ustadz",`<div class="formgrid"><label>Nama Lengkap<input name="name" required></label><label>Username<input name="username" required></label><label>Password<input name="password" type="password" required></label></div>`,async f=>{let u=f.username.value.trim();if(data.profiles.some(x=>x.username===u))return toast("Username sudah digunakan.",true);let {error}=await sb.from("profiles").insert({name:f.name.value.trim(),role:"ustadz",username:u,password:f.password.value});if(error)return toast(error.message,true);closeModal();await loadData();toast("Akun ustadz berhasil dibuat");render()})}
function groupModal(){let us=data.profiles.filter(u=>u.role==="ustadz");if(!us.length)return toast("Buat akun ustadz terlebih dahulu.",true);modal("Buat Kelompok Halaqoh",`<div class="formgrid"><label>Nama Kelompok<input name="name" required></label><label>Ustadz Pembina<select name="ustadzId">${us.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join("")}</select></label></div>`,async f=>{let {error}=await sb.from("groups").insert({name:f.name.value.trim(),ustadz_id:f.ustadzId.value});if(error)return toast(error.message,true);closeModal();await loadData();toast("Kelompok berhasil dibuat");render()})}
async function delStudent(id){if(!confirm("Hapus santri beserta setoran terkait?"))return;await sb.from("records").delete().eq("student_id",id);let {error}=await sb.from("students").delete().eq("id",id);if(error)return toast(error.message,true);await loadData();render()}
async function delUser(id){if(!confirm("Hapus akun ustadz ini?"))return;let {error}=await sb.from("profiles").delete().eq("id",id);if(error)return toast(error.message,true);await loadData();render()}
function pdf(){if(!window.jspdf?.jsPDF){let s=document.createElement("script");s.src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";s.onload=pdf;document.head.appendChild(s);return}let doc=new jspdf.jsPDF({unit:"mm",format:"a4"}),ss=visibleStudents(),rs=data.records.filter(r=>ss.some(s=>s.id===r.student_id));doc.setFillColor(7,63,54);doc.rect(0,0,210,35,"F");doc.setTextColor(255,255,255);doc.setFontSize(18);doc.text("HALAQOH TAHFIDZ ONLINE",15,14);doc.setFontSize(9);doc.text("REKAP PERKEMBANGAN HAFALAN SANTRI",15,23);doc.setTextColor(35,70,63);doc.setFontSize(10);doc.text("Pengelola : "+profile.name,15,46);doc.text("Tanggal : "+new Date().toLocaleDateString("id-ID"),15,53);doc.text(`Santri : ${ss.length}   Setoran : ${rs.length}   Ziyadah : ${rs.filter(r=>r.type==="Ziyadah").length}   Murajaah : ${rs.filter(r=>r.type==="Murajaah").length}`,15,60);let y=73;doc.setFontSize(8);rs.forEach((r,i)=>{if(y>278){doc.addPage();y=18}let n=ss.find(s=>s.id===r.student_id)?.name||"—";doc.text(`${i+1}. ${n.slice(0,25)} | ${r.type} | ${r.from_surah} ${r.from_ayat} → ${r.to_surah} ${r.to_ayat} | ${r.score}`,12,y);y+=7});doc.setTextColor(120,135,130);doc.text("Dokumen dibuat oleh Aplikasi Halaqoh Tahfidz Online",15,289);doc.save("Rekap-Halaqoh-"+new Date().toISOString().slice(0,10)+".pdf")}
function render(){if(!profile)return;nav();let admin=profile.role==="admin",p=location.hash.slice(1)||"dashboard",pages={dashboard,students,groups,users,records,reports},allowed=admin?Object.keys(pages):["dashboard","students","records","reports"];$("#view").innerHTML=pages[allowed.includes(p)?p:"dashboard"]()}
$("#loginForm").onsubmit=e=>{e.preventDefault();login()};$("#togglePassword").onclick=()=>{$("#password").type=$("#password").type==="password"?"text":"password";$("#togglePassword").textContent=$("#password").type==="password"?"Lihat":"Sembunyikan"};$("#logout").onclick=logout;$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");window.addEventListener("hashchange",render);document.addEventListener("keydown",e=>e.key==="Escape"&&closeModal());Object.assign(window,{studentModal,userModal,groupModal,recordModal,delStudent,delUser,pdf,closeModal});
(async()=>{
let {data:{session}}=await sb.auth.getSession();
if(session?.user){
meUser=session.user.id;
let {data:d}=await sb.from("profiles").select("*").eq("id",meUser).maybeSingle();
if(d){profile=d;await enter()}
}
})();})();