(()=>{"use strict";const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],KEY="halaqoh_tahfidz_online_v2";let meUser=null;
const DEFAULT={users:[{id:"u_admin",name:"Administrator",username:"admin",password:"admin123",role:"admin"}],students:[],groups:[],records:[]};
const SURAH=["Al-Fatihah","Al-Baqarah","Ali 'Imran","An-Nisa'","Al-Ma'idah","Al-An'am","Al-A'raf","Al-Anfal","At-Taubah","Yunus","Hud","Yusuf","Ar-Ra'd","Ibrahim","Al-Hijr","An-Nahl","Al-Isra'","Al-Kahf","Maryam","Ta-Ha","Al-Anbiya'","Al-Hajj","Al-Mu'minun","An-Nur","Al-Furqan","Asy-Syu'ara'","An-Naml","Al-Qasas","Al-'Ankabut","Ar-Rum","Luqman","As-Sajdah","Al-Ahzab","Saba'","Fatir","Ya-Sin","As-Saffat","Sad","Az-Zumar","Ghafir","Fussilat","Asy-Syura","Az-Zukhruf","Ad-Dukhan","Al-Jasiyah","Al-Ahqaf","Muhammad","Al-Fath","Al-Hujurat","Qaf","Az-Zariyat","At-Tur","An-Najm","Al-Qamar","Ar-Rahman","Al-Waqi'ah","Al-Hadid","Al-Mujadilah","Al-Hasyr","Al-Mumtahanah","As-Saff","Al-Jumu'ah","Al-Munafiqun","At-Tagabun","At-Talaq","At-Tahrim","Al-Mulk","Al-Qalam","Al-Haqqah","Al-Ma'arij","Nuh","Al-Jinn","Al-Muzzammil","Al-Muddassir","Al-Qiyamah","Al-Insan","Al-Mursalat","An-Naba'","An-Nazi'at","'Abasa","At-Takwir","Al-Infitar","Al-Mutaffifin","Al-Insyiqaq","Al-Buruj","At-Tariq","Al-A'la","Al-Gasyiyah","Al-Fajr","Al-Balad","Asy-Syams","Al-Lail","Ad-Duha","Asy-Syarh","At-Tin","Al-'Alaq","Al-Qadr","Al-Bayyinah","Az-Zalzalah","Al-'Adiyat","Al-Qari'ah","At-Takatsur","Al-'Asr","Al-Humazah","Al-Fil","Quraisy","Al-Ma'un","Al-Kausar","Al-Kafirun","An-Nasr","Al-Lahab","Al-Ikhlas","Al-Falaq","An-Nas"];
const load=()=>{try{let x=JSON.parse(localStorage.getItem(KEY));return x&&x.users&&x.students&&x.groups&&x.records?x:structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}};let db=load();const save=()=>localStorage.setItem(KEY,JSON.stringify(db));const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const uid=p=>p+Date.now()+Math.random().toString(36).slice(2,6),me=()=>db.users.find(x=>x.id===meUser);
function toast(x){let t=$("#toast");t.textContent=x;t.className="show";clearTimeout(window.tt);window.tt=setTimeout(()=>t.className="",2700)}
function closeModal(){$("#modal").innerHTML=""}
function modal(title,body,fn){$("#modal").innerHTML=`<div class="modalbg" id="mb"><div class="modalcard"><div class="modalhead"><h2>${title}</h2><button class="close" type="button" data-close>×</button></div><form id="mf">${body}<div class="actions"><button type="button" class="ghost" data-close>Batal</button><button class="primary">Simpan</button></div></form></div></div>`;let bg=$("#mb"),f=$("#mf");$$("[data-close]",bg).forEach(x=>x.onclick=closeModal);bg.onclick=e=>{if(e.target===bg)closeModal()};f.onsubmit=e=>{e.preventDefault();fn(f)}}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
function login(){let u=$("#username").value.trim(),p=$("#password").value,x=db.users.find(a=>a.username===u&&a.password===p);if(!x){$("#loginError").textContent="Username atau password salah.";$("#loginError").classList.remove("hidden");return}meUser=x.id;sessionStorage.setItem("halaqoh_user",x.id);start()}
function start(){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");render()}
$("#loginForm").onsubmit=e=>{e.preventDefault();login()};$("#logout").onclick=()=>{meUser=null;sessionStorage.removeItem("halaqoh_user");location.hash="";$("#app").classList.add("hidden");$("#login").classList.remove("hidden")};$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");
let saved=sessionStorage.getItem("halaqoh_user");if(saved&&db.users.some(x=>x.id===saved)){meUser=saved;start()}
const visible=()=>me().role==="admin"?db.students:db.students.filter(s=>s.ustadzId===me().id);
function nav(){let admin=me().role==="admin",items=admin?[["dashboard","⌂","Dashboard"],["students","♙","Santri"],["groups","◈","Kelompok"],["users","♟","Akun Ustadz"],["records","✎","Setoran"],["reports","▣","Rekap"]]:[["dashboard","⌂","Dashboard"],["students","♙","Santri Binaan"],["records","✎","Setoran"],["reports","▣","Rekap"]],p=location.hash.slice(1)||"dashboard";$("#nav").innerHTML=items.map(i=>`<button class="nav ${p===i[0]?"active":""}" data-p="${i[0]}"><span>${i[1]}</span>${i[2]}</button>`).join("");$$(".nav").forEach(b=>b.onclick=()=>{location.hash=b.dataset.p;$("#sidebar").classList.remove("open")});$("#who").textContent=me().name+" · "+(admin?"Admin":"Ustadz")}
const shell=(a,b,c="")=>`<div class="head"><div><span class="eyebrow">APLIKASI HALAQOH TAHFIDZ ONLINE</span><h1>${a}</h1><p>${b}</p></div><div>${c}</div></div>`,empty=(a,b)=>`<div style="padding:25px;text-align:center;color:#71827b"><h3>${a}</h3><p>${b}</p></div>`;
function dashboard(){
  let ss=visible(),rs=db.records.filter(r=>ss.some(s=>s.id===r.studentId));
  let z=rs.filter(r=>r.type==='Ziyadah').length,m=rs.filter(r=>r.type==='Murajaah').length;
  let avg=rs.length?(rs.reduce((a,r)=>a+r.score,0)/rs.length).toFixed(1):"—";
  let excellent=rs.filter(r=>r.score>=90).length, good=rs.filter(r=>r.score>=80&&r.score<90).length;
  let recent=[...rs].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);
  let max=Math.max(z,m,1);
  return shell("Dashboard","Semoga Allah mudahkan setiap langkah menjaga Al-Qur'an.")+`
  <div class="stats">
   <div class="stat"><span>👥 Santri</span><b>${ss.length}</b><small>terdaftar</small></div>
   <div class="stat"><span>📖 Ziyadah</span><b>${z}</b><small>setoran hafalan baru</small></div>
   <div class="stat"><span>🔄 Murajaah</span><b>${m}</b><small>setoran pengulangan</small></div>
   <div class="stat"><span>⭐ Rata-rata</span><b>${avg}</b><small>dari ${rs.length} setoran</small></div>
  </div>
  <div class="grid">
   <section class="panel"><div class="panel-title"><h2>📊 Statistik Setoran</h2><span class="badge">${rs.length} total</span></div>
    <div class="chart-row"><div><b>Ziyadah</b><small>${z} setoran</small></div><div class="bar"><i style="width:${z/max*100}%"></i></div><strong>${rs.length?Math.round(z/rs.length*100):0}%</strong></div>
    <div class="chart-row"><div><b>Murajaah</b><small>${m} setoran</small></div><div class="bar"><i style="width:${m/max*100}%"></i></div><strong>${rs.length?Math.round(m/rs.length*100):0}%</strong></div>
    <div class="mini-stats"><div><span>90–100</span><b>${excellent}</b><small>Sangat baik</small></div><div><span>80–89</span><b>${good}</b><small>Baik</small></div><div><span>≤79</span><b>${Math.max(rs.length-excellent-good,0)}</b><small>Perlu perhatian</small></div></div>
   </section>
   <section class="panel"><div class="panel-title"><h2>⚡ Akses Cepat</h2></div><div class="quick">${me().role==='admin'?`<button onclick="studentModal()">＋ Tambah Santri</button><button onclick="groupModal()">＋ Buat Kelompok</button><button onclick="userModal()">＋ Akun Ustadz</button>`:''}<button onclick="recordModal()">＋ Catat Setoran</button><button onclick="location.hash='reports'">▣ Lihat Rekap</button></div></section>
  </div>
  <section class="panel"><div class="panel-title"><h2>📝 Setoran Terbaru</h2><button class="text-btn" onclick="location.hash='records'">Lihat semua →</button></div>
   ${recent.length?`<div class="recent-list">${recent.map(r=>{let s=db.students.find(x=>x.id===r.studentId);return `<div class="recent-item"><div class="recent-icon">${r.type==='Ziyadah'?'📖':'🔄'}</div><div><b>${esc(s?.name||'-')}</b><small><span class="tag ${r.type==='Ziyadah'?'tag-z':'tag-m'}">${esc(r.type)}</span> ${esc(r.fromSurah)} ${esc(r.fromAyat)} → ${esc(r.toSurah)} ${esc(r.toAyat)}</small></div><strong>${r.score}</strong></div>`}).join('')}</div>`:empty('Belum ada setoran','Catatan hafalan akan muncul di sini.')}
  </section>`
}
function studentsPage(){let ss=visible(),admin=me().role==="admin";return shell(admin?"Data Santri":"Santri Binaan","Kelola data santri dan pengelompokan.",admin?`<button class="primary" onclick="studentModal()">＋ Tambah Santri</button>`:"")+`<section class="panel table"><table><thead><tr><th>Nama</th><th>Kelas</th><th>Kelompok</th><th>Setoran</th>${admin?"<th>Aksi</th>":""}</tr></thead><tbody>${ss.length?ss.map(s=>{let g=db.groups.find(x=>x.id===s.groupId);return`<tr><td><b>${esc(s.name)}</b></td><td>${esc(s.className||"-")}</td><td>${esc(g?.name||"-")}</td><td>${db.records.filter(r=>r.studentId===s.id).length}</td>${admin?`<td><button class="mini danger" onclick="delStudent('${s.id}')">Hapus</button></td>`:""}</tr>`}).join(""):`<tr><td colspan="5">${empty("Belum ada santri","Tambahkan santri terlebih dahulu.")}</td></tr>`}</tbody></table></section>`}
function groupsPage(){return shell("Kelompok Halaqoh","Atur kelompok dan ustadz pembina.",`<button class="primary" onclick="groupModal()">＋ Buat Kelompok</button>`)+`<section class="cards">${db.groups.length?db.groups.map(g=>{let u=db.users.find(x=>x.id===g.ustadzId);return`<div class="card"><h3>${esc(g.name)}</h3><p class="muted">Ustadz: ${esc(u?.name||"-")}</p><b>${db.students.filter(s=>s.groupId===g.id).length} santri</b></div>`}).join(""):empty("Belum ada kelompok","Buat kelompok setelah akun ustadz tersedia.")}</section>`}
function usersPage(){let us=db.users.filter(x=>x.role==="ustadz");return shell("Akun Ustadz","Admin membuat dan mengelola akun ustadz.",`<button class="primary" onclick="userModal()">＋ Buat Akun</button>`)+`<section class="cards">${us.length?us.map(u=>`<div class="card"><h3>${esc(u.name)}</h3><p class="muted">@${esc(u.username)}</p><button class="mini danger" onclick="delUser('${u.id}')">Hapus</button></div>`).join(""):empty("Belum ada akun","Buat akun ustadz.")}</section>`}
const opts=()=>SURAH.map((s,i)=>`<option value="${esc(s)}">${i+1}. ${esc(s)}</option>`).join("");
function recordModal(){let ss=visible();if(!ss.length)return toast("Belum ada santri.");modal("Catat Setoran Hafalan",`<div class="formgrid"><label>Santri<select name="studentId">${ss.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("")}</select></label><label>Jenis Setoran<select name="type"><option value="Ziyadah">📖 Ziyadah</option><option value="Murajaah">🔄 Murajaah</option></select></label><label>Dari Surat<select name="fromSurah">${opts()}</select></label><label>Dari Ayat<input name="fromAyat" type="number" min="1" required placeholder="Contoh: 1"></label><label>Sampai Surat<select name="toSurah">${opts()}</select></label><label>Sampai Ayat<input name="toAyat" type="number" min="1" required placeholder="Contoh: 10"></label><label>Tanggal<input name="date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Nilai<select name="score"><option value="90">90 — Sangat Baik</option><option value="80">80 — Baik</option><option value="70">70 — Cukup</option><option value="60">60 — Perlu Murajaah</option></select></label><label style="grid-column:1/-1">Catatan<input name="note" placeholder="Catatan ustadz"></label></div>`,f=>{let a=SURAH.indexOf(f.fromSurah.value),b=SURAH.indexOf(f.toSurah.value),fa=+f.fromAyat.value,ta=+f.toAyat.value;if(a>b||(a===b&&fa>ta))return toast("Rentang hafalan tidak valid.");db.records.push({id:uid("r"),studentId:f.studentId.value,type:f.type.value,fromSurah:f.fromSurah.value,fromAyat:fa,toSurah:f.toSurah.value,toAyat:ta,surah:f.fromSurah.value,ayat:fa+"-"+ta,date:f.date.value,score:+f.score.value,note:f.note.value});save();closeModal();toast("Setoran tersimpan");render()})}
function recordsPage(){let ss=visible(),rs=db.records.filter(r=>ss.some(s=>s.id===r.studentId)).sort((a,b)=>b.date.localeCompare(a.date));return shell("Setoran Hafalan","Ziyadah dan murajaah tercatat lengkap dari surat & ayat awal sampai akhir.",`<button class="primary" onclick="recordModal()">＋ Catat Setoran</button>`)+`<section class="panel table"><table><thead><tr><th>Tanggal</th><th>Santri</th><th>Jenis</th><th>Dari</th><th>Sampai</th><th>Nilai</th><th>Catatan</th></tr></thead><tbody>${rs.length?rs.map(r=>{let s=db.students.find(x=>x.id===r.studentId);return`<tr><td>${r.date}</td><td><b>${esc(s?.name)}</b></td><td>${esc(r.type)}</td><td>${esc(r.fromSurah)} · Ayat ${esc(r.fromAyat)}</td><td>${esc(r.toSurah)} · Ayat ${esc(r.toAyat)}</td><td class="score">${r.score}</td><td>${esc(r.note||"-")}</td></tr>`}).join(""):`<tr><td colspan="7">${empty("Belum ada setoran","Mulai catat setoran untuk melihat perkembangan.")}</td></tr>`}</tbody></table></section>`}
function reportsPage(){
  let ss=visible(),rs=db.records.filter(r=>ss.some(s=>s.id===r.studentId));
  let z=rs.filter(r=>r.type==='Ziyadah').length,m=rs.filter(r=>r.type==='Murajaah').length;
  let avg=rs.length?(rs.reduce((a,r)=>a+r.score,0)/rs.length).toFixed(1):"—";
  return shell("Rekap Perkembangan","Pantau perkembangan ziyadah dan murajaah santri secara lengkap.",`<button class="primary" onclick="pdf()">↓ Unduh PDF Keren</button>`)+`
  <section class="panel">
   <div class="summary"><div><span>👥 Santri</span><b>${ss.length}</b><small>terdaftar</small></div><div><span>📖 Ziyadah</span><b>${z}</b><small>setoran</small></div><div><span>🔄 Murajaah</span><b>${m}</b><small>setoran</small></div><div><span>⭐ Rata-rata</span><b>${avg}</b><small>nilai hafalan</small></div></div>
   <div class="table"><table><thead><tr><th>Santri</th><th>Ziyadah</th><th>Murajaah</th><th>Total</th><th>Rata-rata</th><th>Hafalan Terakhir</th></tr></thead><tbody>${ss.length?ss.map(s=>{let a=rs.filter(r=>r.studentId===s.id),zz=a.filter(r=>r.type==='Ziyadah').length,mm=a.filter(r=>r.type==='Murajaah').length,av=a.length?(a.reduce((x,r)=>x+r.score,0)/a.length).toFixed(1):'—',l=a[a.length-1];return `<tr><td><b>${esc(s.name)}</b></td><td><span class="pill z">${zz}</span></td><td><span class="pill m">${mm}</span></td><td>${a.length}</td><td>${av}</td><td>${l?esc(l.fromSurah)+' '+esc(l.fromAyat)+' → '+esc(l.toSurah)+' '+esc(l.toAyat):'—'}</td></tr>`}).join(''):`<tr><td colspan="6">${empty('Belum ada data','Tambahkan setoran terlebih dahulu.')}</td></tr>`}</tbody></table></div>
  </section>`
}
function studentModal(){modal("Tambah Santri",`<div class="formgrid"><label>Nama<input name="name" required></label><label>Kelas<input name="className" placeholder="Contoh: 8A"></label><label>Kelompok<select name="groupId"><option value="">Belum dikelompokkan</option>${db.groups.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join("")}</select></label></div>`,f=>{let g=db.groups.find(x=>x.id===f.groupId.value);db.students.push({id:uid("s"),name:f.name.value.trim(),className:f.className.value.trim(),groupId:g?.id||"",ustadzId:g?.ustadzId||""});save();closeModal();toast("Santri ditambahkan");render()})}
function userModal(){modal("Buat Akun Ustadz",`<div class="formgrid"><label>Nama<input name="name" required></label><label>Username<input name="username" required></label><label>Password<input name="password" required></label></div>`,f=>{let u=f.username.value.trim();if(db.users.some(x=>x.username===u))return toast("Username sudah digunakan.");db.users.push({id:uid("u"),name:f.name.value.trim(),username:u,password:f.password.value,role:"ustadz"});save();closeModal();toast("Akun ustadz dibuat");render()})}
function groupModal(){let us=db.users.filter(u=>u.role==="ustadz");if(!us.length)return toast("Buat akun ustadz dulu.");modal("Buat Kelompok Halaqoh",`<div class="formgrid"><label>Nama Kelompok<input name="name" required placeholder="Halaqoh A"></label><label>Ustadz<select name="ustadzId">${us.map(u=>`<option value="${u.id}">${esc(u.name)}</option>`).join("")}</select></label></div>`,f=>{db.groups.push({id:uid("g"),name:f.name.value.trim(),ustadzId:f.ustadzId.value});save();closeModal();toast("Kelompok dibuat");render()})}
function delStudent(id){if(confirm("Hapus santri dan seluruh setoran santri ini?")){db.students=db.students.filter(x=>x.id!==id);db.records=db.records.filter(x=>x.studentId!==id);save();render()}}
function delUser(id){if(confirm("Hapus akun ustadz ini?")){db.users=db.users.filter(x=>x.id!==id);db.groups=db.groups.map(g=>g.ustadzId===id?{...g,ustadzId:""}:g);db.students=db.students.map(s=>s.ustadzId===id?{...s,ustadzId:""}:s);save();render()}}
function pdf(){
  if(!window.jspdf?.jsPDF)return toast("PDF belum siap. Periksa koneksi internet lalu coba lagi.");
  const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});
  const ss=visible(),rs=db.records.filter(r=>ss.some(s=>s.id===r.studentId));
  const z=rs.filter(r=>r.type==='Ziyadah').length,m=rs.filter(r=>r.type==='Murajaah').length;
  const avg=rs.length?(rs.reduce((a,r)=>a+r.score,0)/rs.length).toFixed(1):'—';
  const pageW=210, margin=14;
  const teal=[15,118,110],dark=[22,54,48],light=[235,247,243],gold=[184,134,11],muted=[91,110,103];
  const footer=()=>{doc.setDrawColor(210,222,218);doc.line(margin,286,pageW-margin,286);doc.setFontSize(7);doc.setTextColor(...muted);doc.text('Aplikasi Halaqoh Tahfidz Online',margin,292);doc.text('Halaman '+doc.getNumberOfPages(),pageW-margin,292,{align:'right'})};
  const header=()=>{doc.setFillColor(...teal);doc.roundedRect(0,0,pageW,39,0,0,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(16);doc.text('APLIKASI HALAQOH TAHFIDZ ONLINE',margin,14);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('REKAP PERKEMBANGAN HAFALAN SANTRI',margin,21);doc.setFontSize(8);doc.text('Pengelola: '+(me()?.name||'-'),margin,29);doc.text(new Date().toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'}),pageW-margin,29,{align:'right'});};
  header();
  doc.setTextColor(...dark);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('RINGKASAN',margin,51);
  const cards=[['SANTRI',String(ss.length)],['TOTAL SETORAN',String(rs.length)],['ZIYADAH',String(z)],['MURAJAAH',String(m)],['RATA-RATA',String(avg)]];
  cards.forEach((c,i)=>{let x=margin+i*36.3;doc.setFillColor(...light);doc.roundedRect(x,57,33.5,23,3,3,'F');doc.setTextColor(...muted);doc.setFontSize(6.5);doc.text(c[0],x+3,64);doc.setTextColor(...dark);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text(c[1],x+3,74);});
  let y=91;doc.setFontSize(11);doc.setTextColor(...dark);doc.text('DAFTAR SETORAN',margin,y);y+=7;
  const cols=[margin,32,67,94,128,168];
  const widths=[18,35,27,34,40,28];
  const head=['No','Santri','Jenis','Dari','Sampai','Nilai'];
  const drawHead=()=>{doc.setFillColor(...teal);doc.roundedRect(margin,y-5,182,8,1.5,1.5,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(7);head.forEach((h,i)=>doc.text(h,cols[i]+2,y));y+=8};
  drawHead();
  rs.sort((a,b)=>b.date.localeCompare(a.date)).forEach((r,i)=>{if(y>274){footer();doc.addPage();header();y=51;doc.setTextColor(...dark);doc.setFontSize(11);doc.text('DAFTAR SETORAN (LANJUTAN)',margin,y);y+=7;drawHead()}let s=db.students.find(x=>x.id===r.studentId);if(i%2===0){doc.setFillColor(248,251,250);doc.rect(margin,y-4,182,7,'F')}doc.setTextColor(...dark);doc.setFont('helvetica','normal');doc.setFontSize(7);doc.text(String(i+1),cols[0]+2,y);doc.text((s?.name||'-').slice(0,20),cols[1]+2,y);doc.text(r.type,cols[2]+2,y);doc.text((r.fromSurah+' '+r.fromAyat).slice(0,20),cols[3]+2,y);doc.text((r.toSurah+' '+r.toAyat).slice(0,22),cols[4]+2,y);doc.setFont('helvetica','bold');doc.text(String(r.score),cols[5]+2,y);y+=7});
  if(!rs.length){doc.setTextColor(...muted);doc.setFont('helvetica','normal');doc.text('Belum ada data setoran.',margin,y+5)}
  footer();doc.save('Rekap-Halaqoh-Tahfidz-Online-'+new Date().toISOString().slice(0,10)+'.pdf');toast('PDF keren berhasil diunduh');
}
function render(){if(!meUser)return;nav();let p=location.hash.slice(1)||"dashboard",admin=me().role==="admin",allowed=admin?["dashboard","students","groups","users","records","reports"]:["dashboard","students","records","reports"];if(!allowed.includes(p))p="dashboard";$("#view").innerHTML={dashboard,students:studentsPage,groups:groupsPage,users:usersPage,records:recordsPage,reports:reportsPage}[p]}
window.addEventListener("hashchange",render);Object.assign(window,{studentModal,userModal,groupModal,recordModal,delStudent,delUser,pdf,closeModal});
})();